USE [master]
GO
/****** Object:  Database [Configuracao]    Script Date: 16/03/2023 13:58:36 ******/
CREATE DATABASE [Configuracao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Configuracao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019A\MSSQL\DATA\Configuracao.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Configuracao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019A\MSSQL\DATA\Configuracao_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Configuracao] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Configuracao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Configuracao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Configuracao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Configuracao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Configuracao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Configuracao] SET ARITHABORT OFF 
GO
ALTER DATABASE [Configuracao] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Configuracao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Configuracao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Configuracao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Configuracao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Configuracao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Configuracao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Configuracao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Configuracao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Configuracao] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Configuracao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Configuracao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Configuracao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Configuracao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Configuracao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Configuracao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Configuracao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Configuracao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Configuracao] SET  MULTI_USER 
GO
ALTER DATABASE [Configuracao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Configuracao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Configuracao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Configuracao] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Configuracao] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Configuracao] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Configuracao] SET QUERY_STORE = OFF
GO
USE [Configuracao]
GO
/****** Object:  Table [dbo].[GpUsuario_Permissao]    Script Date: 16/03/2023 13:58:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GpUsuario_Permissao](
	[Cod_permissao] [int] NOT NULL,
	[Cod_gpusuario] [int] NOT NULL,
 CONSTRAINT [PK_GpUsuario_Permissao] PRIMARY KEY CLUSTERED 
(
	[Cod_permissao] ASC,
	[Cod_gpusuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grupo_Usuario]    Script Date: 16/03/2023 13:58:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grupo_Usuario](
	[IDGrupo] [int] IDENTITY(1,1) NOT NULL,
	[NomeGrupo] [varchar](150) NULL,
 CONSTRAINT [PK_Grupo_Usuario] PRIMARY KEY CLUSTERED 
(
	[IDGrupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissão]    Script Date: 16/03/2023 13:58:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissão](
	[ID_permi] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](250) NULL,
 CONSTRAINT [PK_Permissão] PRIMARY KEY CLUSTERED 
(
	[ID_permi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 16/03/2023 13:58:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[ID_usuario] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](60) NULL,
	[Email] [varchar](50) NULL,
	[CPF] [varchar](14) NULL,
	[Ativo] [bit] NULL,
	[Nome_de_usuario] [varchar](60) NULL,
	[Senha] [varchar](50) NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario_GrupoUsuario]    Script Date: 16/03/2023 13:58:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario_GrupoUsuario](
	[Cod_usuario] [int] NOT NULL,
	[Cod_grupousuario] [int] NOT NULL,
 CONSTRAINT [PK_Usuario_GrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[Cod_usuario] ASC,
	[Cod_grupousuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GpUsuario_Permissao]  WITH CHECK ADD  CONSTRAINT [FK_GpUsuario_Permissao_Grupo_Usuario] FOREIGN KEY([Cod_gpusuario])
REFERENCES [dbo].[Grupo_Usuario] ([IDGrupo])
GO
ALTER TABLE [dbo].[GpUsuario_Permissao] CHECK CONSTRAINT [FK_GpUsuario_Permissao_Grupo_Usuario]
GO
ALTER TABLE [dbo].[GpUsuario_Permissao]  WITH CHECK ADD  CONSTRAINT [FK_GpUsuario_Permissao_Permissão] FOREIGN KEY([Cod_permissao])
REFERENCES [dbo].[Permissão] ([ID_permi])
GO
ALTER TABLE [dbo].[GpUsuario_Permissao] CHECK CONSTRAINT [FK_GpUsuario_Permissao_Permissão]
GO
ALTER TABLE [dbo].[Usuario_GrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_GrupoUsuario_Grupo_Usuario] FOREIGN KEY([Cod_grupousuario])
REFERENCES [dbo].[Grupo_Usuario] ([IDGrupo])
GO
ALTER TABLE [dbo].[Usuario_GrupoUsuario] CHECK CONSTRAINT [FK_Usuario_GrupoUsuario_Grupo_Usuario]
GO
ALTER TABLE [dbo].[Usuario_GrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_GrupoUsuario_Usuario] FOREIGN KEY([Cod_usuario])
REFERENCES [dbo].[Usuario] ([ID_usuario])
GO
ALTER TABLE [dbo].[Usuario_GrupoUsuario] CHECK CONSTRAINT [FK_Usuario_GrupoUsuario_Usuario]
GO
USE [master]
GO
ALTER DATABASE [Configuracao] SET  READ_WRITE 
GO
